<a href="https://colab.research.google.com/github/acruzca/ia-bigdata-learning/blob/main/02-numpy-pandas/02-arrays-matrices-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 02 - Arrays y matrices con NumPy

## Objetivo

Aprender a trabajar con arrays de varias dimensiones y comprender las propiedades fundamentales de los arrays de NumPy.

## Conceptos utilizados

- Dimensiones de un array
- `ndim`
- `shape`
- `size`
- `dtype`
- Arrays bidimensionales
- Acceso a filas y columnas
- `reshape`
- Operaciones con matrices

In [1]:
import numpy as np

# Array de una dimensión
ventas = np.array([1200, 950, 1430, 1100, 1750, 1620])

print("Array:", ventas)
print("Dimensiones:", ventas.ndim)
print("Forma:", ventas.shape)
print("Número de elementos:", ventas.size)
print("Tipo de datos:", ventas.dtype)

Array: [1200  950 1430 1100 1750 1620]
Dimensiones: 1
Forma: (6,)
Número de elementos: 6
Tipo de datos: int64


## Arrays bidimensionales

Un array bidimensional puede interpretarse como una tabla formada por filas y columnas.

En Machine Learning es habitual representar un conjunto de datos mediante una matriz donde las filas representan observaciones y las columnas representan características.

In [4]:
datos = np.array([
    [1200, 5, 100],
    [950, 3, 80],
    [1430, 6, 120],
    [1100, 4, 90]
])

print(datos)

print("Dimensiones:", datos.ndim)
print("Forma:", datos.shape)
print("Número de elementos:", datos.size)

print(datos[0, 0])
print(datos[1, 2])
print(datos[3, 1])

print("Primera fila:", datos[0])
print("Segunda fila:", datos[1])

print("Primera columna:", datos[:, 0])
print("Segunda columna:", datos[:, 1])
print("Tercera columna:", datos[:, 2])


[[1200    5  100]
 [ 950    3   80]
 [1430    6  120]
 [1100    4   90]]
Dimensiones: 2
Forma: (4, 3)
Número de elementos: 12
1200
80
4
Primera fila: [1200    5  100]
Segunda fila: [950   3  80]
Primera columna: [1200  950 1430 1100]
Segunda columna: [5 3 6 4]
Tercera columna: [100  80 120  90]


In [8]:
import numpy as np

empleados = np.array([
    [35, 32000, 5],
    [52, 44000, 15],
    [28, 27000, 2],
    [46, 51000, 12],
    [41, 39000, 8]
])

#1. Número de dimensiones.
numero_dimensiones = empleados.ndim
print("Dimensiones:", numero_dimensiones)
#2. Forma de la matriz.
forma_matriz = empleados.shape
print("Forma:", forma_matriz)
#3. Número total de elementos.
total_elementos = empleados.size
print("Número de elementos:", total_elementos)
#4. Segunda fila completa.
segunda_fila = empleados[1]
print("Segundo empleado:", segunda_fila)
#5. Edad del cuarto empleado.
edad_cuarto_empleado = empleados[3,0]
print("Edad del cuarto empleado:", edad_cuarto_empleado)
#6. Todas las edades.
edades = empleados[:,0]
print("Edades:", edades)
#7. Todos los salarios.
salarios = empleados[:,1]
print("Salarios:", salarios)
#8. Salario medio.
salario_medio = np.mean(salarios)
print("Salario medio:", salario_medio, "€")
#9. Edad media.
edad_media = np.mean(edades)
print("Edad media:", edad_media)
#10. Empleados cuyo salario sea superior a 40.000 €
mascara_salarios = salarios > 40000
print("Mascara:", mascara_salarios)
salario_superior = empleados[mascara_salarios]
print("Empleados con salario superior a 40.000 €:")
print(salario_superior)


Dimensiones: 2
Forma: (5, 3)
Número de elementos: 15
Segundo empleado: [   52 44000    15]
Edad del cuarto empleado: 46
Edades: [35 52 28 46 41]
Salarios: [32000 44000 27000 51000 39000]
Salario medio: 38600.0 €
Edad media: 40.4
Mascara: [False  True False  True False]
Empleados con salario superior a 40.000 €:
[[   52 44000    15]
 [   46 51000    12]]


## 5. Cambiar la forma de un array con `reshape`

NumPy permite cambiar la estructura de un array mediante `reshape()` sin modificar sus datos.

Para poder cambiar la forma, el número total de elementos debe mantenerse.

In [12]:
numeros = np.array([1, 2, 3, 4, 5, 6])

print("Array original:")
print(numeros)

print("Forma:", numeros.shape)

matriz_2x3 = numeros.reshape(2, 3)

print(matriz_2x3)
print("Forma:", matriz_2x3.shape)

matriz_3x2 = numeros.reshape(3, 2)

print(matriz_3x2)
print("Forma:", matriz_3x2.shape)

matriz = numeros.reshape(-1, 2)

print(matriz)
print(matriz.shape)

matriz = numeros.reshape(2, -1)

print(matriz)

Array original:
[1 2 3 4 5 6]
Forma: (6,)
[[1 2 3]
 [4 5 6]]
Forma: (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Forma: (3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 3]
 [4 5 6]]


## 7. Operaciones con matrices

NumPy permite realizar operaciones matemáticas sobre matrices.

Es importante distinguir entre las operaciones elemento a elemento y la multiplicación matricial.

In [18]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matriz A:")
print(A)

print("\nMatriz B:")
print(B)

print(A+B)

print(A*B)

resultado = A @ B

print(resultado)

matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original:")
print(matriz)

print("\nTranspuesta:")
print(matriz.T)


print("Forma original:", matriz.shape)
print("Forma transpuesta:", matriz.T.shape)

Matriz A:
[[1 2]
 [3 4]]

Matriz B:
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
Original:
[[1 2 3]
 [4 5 6]]

Transpuesta:
[[1 4]
 [2 5]
 [3 6]]
Forma original: (2, 3)
Forma transpuesta: (3, 2)


In [28]:
import numpy as np

datos = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

#1. Número de dimensiones
print("Dimensiones:", datos.ndim)
#2. Forma
print("Forma:", datos.shape)
#3. size
print("Tamaño:", datos.size)
#4. Primera fila.
print("Primera fila:", datos[0])
#5. Tercera columna.
print("Tercera columna:", datos[:,2])
#6. Elemento de la fila 3, columna 2 (teniendo en cuenta que Python empieza en 0).
print("Elemento:", datos[2,1])
#7. Media de todos los valores.
print("Media:", np.mean(datos))
#8. Valores mayores de 60.
mayores_60 = datos[datos > 60]
print("Valores mayores de 60:", mayores_60)
#9. Matriz transpuesta
transpuesta = datos.T
print("Matriz transpuesta:")
print(transpuesta)
#10. Forma de la matriz transpuesta.
print("Forma trasnpuesta:", transpuesta.shape)
#11. Convertir a una matriz 2 x 6
matriz_2x6 = datos.reshape(2,6)
print("Matriz 2x6:")
print(matriz_2x6)
#12. Matriz con 3 columnas utilizando reshape(-1, 3).
matriz_3_columnas = datos.reshape(-1,3)
print("Matriz 3 columnas:")
print(matriz_3_columnas)


Dimensiones: 2
Forma: (4, 3)
Tamaño: 12
Primera fila: [10 20 30]
Tercera columna: [ 30  60  90 120]
Elemento: 80
Media: 65.0
Valores mayores de 60: [ 70  80  90 100 110 120]
Matriz transpuesta:
[[ 10  40  70 100]
 [ 20  50  80 110]
 [ 30  60  90 120]]
Forma trasnpuesta: (3, 4)
Matriz 2x6:
[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]
Matriz 3 columnas:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
